#!/usr/bin/env node
/**
 * Generates the model types for both languages from spec/v1/sql-schema.json.
 *
 * The spec is the single source of the payload shape, so the models are not hand-written beside
 * it. Output is committed so a spec change is reviewable as a diff of the public API -- which
 * matters more here than usual: these packages are published, so a change to a generated type is a
 * change to somebody else's compile.
 *
 *   node scripts/codegen.mjs            rewrite the generated sources
 *   node scripts/codegen.mjs --check    exit 1 if any is out of date
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import prettier from "prettier";
import { compile } from "json-schema-to-typescript";
import { emitCSharp } from "./emit-csharp.mjs";

const ROOT = new URL("..", import.meta.url).pathname;
const SPEC = join(ROOT, "spec/v1/sql-schema.json");

const BANNER = `/*
 * GENERATED FILE -- do not edit.
 *
 * Produced from spec/v1/sql-schema.json by \`npm run codegen\`. Edit the spec, then regenerate;
 * \`npm run codegen:check\` fails CI when the two have drifted.
 */
`;

const check = process.argv.includes("--check");
const stale = [];

function settle(path, contents) {
  const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (existing === contents) return;
  if (check) {
    stale.push(relative(ROOT, path));
    return;
  }
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, contents, "utf8");
}

/**
 * `emit-csharp.mjs` indents every type by four spaces, which is right for a block-scoped namespace
 * -- but it emits a FILE-scoped one (`namespace X;`), under which a type belongs at column zero.
 *
 * The emitter is kept byte-identical to the copies in the cli-schema and kps-docs repositories,
 * deliberately, so the correction is applied here rather than by forking it. Both of those
 * repositories have the same four-space offset in their committed output today; neither has
 * noticed, because `// <auto-generated />` makes `dotnet format` and the IDE analyzers skip the
 * file. That is precisely the trap AGENTS.md warns about, and it is why the check below exists.
 */
function dedentFileScopedNamespace(source) {
  return source
    .split("\n")
    .map((line) => (line.startsWith("    ") ? line.slice(4) : line))
    .join("\n");
}

/**
 * ⚠️ `dotnet format` skips a file with an `// <auto-generated />` header entirely, so the C# style
 * gate in CI cannot see this output -- the generator has to be what enforces the style.
 *
 * K&R means an opening brace never gets a line of its own, and `else`/`catch`/`finally` never
 * start one. Indentation is checked alongside it because IDE0055 covers both and neither is
 * visible to the formatter here. Checked rather than trusted, because the whole point of the
 * `<auto-generated />` trap is that the divergence is silent.
 */
function assertCSharpStyle(source, path) {
  const offenders = [];
  source.split("\n").forEach((line, index) => {
    const at = index + 1;
    if (/^\s*\{\s*$/.test(line)) offenders.push([at, line, "opening brace on its own line"]);
    else if (/^\s*(else|catch|finally)\b/.test(line))
      offenders.push([at, line, "`else`/`catch`/`finally` starting a line"]);
    else if (/^\s+(public|internal|private)\s+(sealed\s+)?(record|class|partial)\b/.test(line))
      offenders.push([at, line, "type indented under a file-scoped namespace"]);
  });
  if (offenders.length === 0) return;
  console.error(`${relative(ROOT, path)} does not match the repository's C# style.`);
  console.error(`dotnet format cannot catch this: the <auto-generated /> header makes it skip the`);
  console.error(`file entirely. Offending lines:\n`);
  for (const [number, line, why] of offenders) console.error(`  ${number}: ${why}\n      ${line}`);
  process.exit(1);
}

const schema = JSON.parse(readFileSync(SPEC, "utf8"));

// The root `title` and `$id` are dropped so the generator takes the name passed to it; it falls
// back to `$id` otherwise. The `$defs` titles are kept -- those ARE the published type names.
const rootless = { ...schema };
delete rootless.title;
delete rootless.$id;

const prettierConfig = await prettier.resolveConfig(join(ROOT, "package.json"));

const options = {
  bannerComment: "",
  declareExternallyReferenced: true,
  additionalProperties: false,
  enableConstEnums: false,
};

const ts = await compile(rootless, "SqlSchemaDescription", options);

// SqlAnnotations is reachable from nothing in the payload -- it is a separate document a producer
// is handed, not something a producer writes -- so it has to be compiled in its own pass. Its
// $defs are carried across so any shared definition resolves; the duplicate declarations that
// produces are dropped, keeping the ones from the payload pass.
const annotationsSchema = { ...schema.$defs.annotations, $defs: schema.$defs };
const annotationsTs = await compile(annotationsSchema, "SqlAnnotations", options);
const already = new Set([...ts.matchAll(/export (?:interface|type) (\w+)/g)].map((m) => m[1]));
const annotationsOnly = annotationsTs
  .split(/(?=export (?:interface|type) )/)
  .filter((block) => {
    const name = /export (?:interface|type) (\w+)/.exec(block)?.[1];
    return name !== undefined && !already.has(name);
  })
  .join("");

settle(
  join(ROOT, "packages/sql-schema/src/generated/types.ts"),
  await prettier.format(BANNER + ts + annotationsOnly, {
    ...prettierConfig,
    parser: "typescript",
  }),
);

const csharp = dedentFileScopedNamespace(
  emitCSharp({
    schema,
    rootName: "SqlSchemaDescription",
    namespace: "CairnTool.SqlSchema",
    // Generated, unlike cli-schema's. That repository keeps a hand-written context because a
    // published 1.0.0 wire format already depends on its options; nothing is published here yet, so
    // the options are fixed at the first commit and generated from then on.
    contextName: "SqlSchemaJsonContext",
    // Init, not positional. SqlTable has eight members and SqlColumn seven; a primary constructor at
    // that arity is unreadable, and no constructor API has been published that would be broken by
    // choosing properties instead.
    style: "init",
  }),
);

// The npm package ships the schema document as a runtime export, so it needs its own copy inside
// `src`. cli-schema commits that copy by hand and asserts equality in a test; settling it here
// instead means `codegen:check` is what catches a divergence, which is one gate rather than two.
settle(join(ROOT, "packages/sql-schema/src/sql-schema.json"), readFileSync(SPEC, "utf8"));

const csharpPath = join(ROOT, "dotnet/src/CairnTool.SqlSchema/Generated/Models.cs");
assertCSharpStyle(csharp, csharpPath);
settle(csharpPath, csharp);

if (check && stale.length > 0) {
  console.error("These generated sources are out of date. Run `npm run codegen`:\n");
  for (const path of stale) console.error(`  ${path}`);
  process.exit(1);
}

console.log(check ? "generated sources are current" : "generated sources rebuilt");
